server:
  port: 8585
spring:
  application:
    name: seguros
  datasource:
    username: 'postgres'
    url: jdbc:postgresql://localhost:5432/Seguros
    password: 'password'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    hibernate:
      ddl-auto: update
    show-sql: 'true'
